title = "Francesco"
baseURL = "https://francesco.cc"

theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally

[services]
  [services.googleAnalytics]
    id = ""  # add your tracking id

[params]
  author = "Francesco Pompo'"
  description = ""
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = "/images/logo.svg"  # url or path to a logo to put in the header
  [params.footer]
    text = ""
    url = "https://github.com/deade1e"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    fontSize = "12pt"
    pageWidth = "750px"
    avatarSize = "90px"
    colorDark = "#111"
    colorLight = "#fff"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "Linkedin"
    url = "https://linkedin.com/in/francescopompo"
  [[params.socialIcons]]
    icon = "fa fa-envelope"
    title = "E-mail"
    url = "mailto:contact@francesco.cc"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/deade1e"
  [[params.socialIcons]]
    icon = "fa fa-rss"
    title = "RSS"
    url = "/index.xml"

[permalinks]
  "/" = "/:contentbasename"

[menu]

  [[menu.main]]
    weight = 1
    identifier = "about"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "About"
    url = "/about"
    # title will be shown when you hover on this menu link
    title = "About"
  [[menu.main]]
    weight = 2
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = "Posts"
  [[menu.main]]
    weight = 3
    identifier = "resume"
    pre = ""
    post = ""
    name = "Resume"
    url = "/resume"
    title = "Resume"

[markup.highlight]
  style = "hr_high_contrast"

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
