title = "Francesco"
baseURL = "https://francesco.cc"

theme = "researcher"
# disableKinds = ["term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally

[services]
  [services.googleAnalytics]
    id = "G-2K6FXB19TQ"  # add your tracking id

[params]
  author = "Francesco Pompo'"
  description = ""
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = "/images/logo.svg"  # url or path to a logo to put in the header
  [params.footer]
    text = ""
    url = "https://github.com/deade1e"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    fontSize = "12pt"
    pageWidth = "750px"
    avatarSize = "90px"
    colorDark = "#fff"
    colorLight = "#000"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "Linkedin"
    url = "https://linkedin.com/in/francescopompo"
  [[params.socialIcons]]
    icon = "fa fa-envelope"
    title = "E-mail"
    url = "mailto:contact@francesco.cc"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/deade1e"
  [[params.socialIcons]]
    icon = "fab fa-x-twitter"
    title = "X"
    url = "https://x.com/deade1e"
  [[params.socialIcons]]
    icon = "fa fa-rss"
    title = "RSS"
    url = "/index.xml"

[permalinks]
  "/" = "/:contentbasename"

[menu]

  [[menu.main]]
    name = "About"
    url = "/about"
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
  [[menu.main]]
    name = "Resume"
    url = "/resume"

[markup.highlight]
  style = "github"

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
